# Generated by Django 3.0.8 on 2020-07-06 10:50

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.FileField(upload_to=portfolio.models.image_upload)),
                ('about_title_help', models.CharField(max_length=400)),
                ('about_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_title_help',
        ),
        migrations.AddField(
            model_name='homeslider',
            name='subtitle',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(upload_to=portfolio.models.image_upload),
        ),
        migrations.AlterField(
            model_name='casework',
            name='image',
            field=models.FileField(upload_to=portfolio.models.image_upload),
        ),
        migrations.AlterField(
            model_name='companybrand',
            name='company_logo',
            field=models.FileField(upload_to=portfolio.models.image_upload),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.FileField(upload_to=portfolio.models.image_upload),
        ),
        migrations.AlterField(
            model_name='service',
            name='about_image',
            field=models.FileField(upload_to=portfolio.models.image_upload),
        ),
    ]
