# Generated by Django 3.0.8 on 2020-07-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
